POST http://localhost:8081/api/Authentication/SignUp
content-Type: application/json

{
  "last_name": "Adminov",
  "first_name": "Admin",
  "username": "admin",
  "password": "admin"
}

POST http://localhost:8081/api/Authentication/SignIn
content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


POST http://localhost:8081/api/Authentication/Refresh
content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJhZG1pbiJdLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNzI3NTMwMzA0LCJzdWIiOiJhZG1pbiJ9.NUdy3c5zSdvFL8yh_w1sXLn8HOA0qIlEGSbk3eVaz1Y"
}


PUT http://localhost:8081/api/Authentication/SignOut


GET http://localhost:8081/api/Authentication/Validate?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6WyJ1c2VyIl0sInVzZXJuYW1lIjoiZnJlZHkxMjkwNTMiLCJleHAiOjE3MjczMTQzMTksInN1YiI6ImZyZWR5MTI5MDUzIn0.A-723_Uya6Xw5iyuE2VIPCjen3w7N7OjWFRZCJaiTU0


GET http://localhost:8081/api/Accounts/Me


PUT http://localhost:8081/api/Accounts/Update
content-Type: application/json

{
  "first_name": "Rodion",
  "last_name": "Ok",
  "password": "1122333"
}

GET http://localhost:8081/api/Accounts?from=1&count=10

POST http://localhost:8081/api/Accounts
content-Type: application/json

{
  "first_name": "User",
  "last_name": "Userov",
  "username": "user",
  "password": "user",
  "roles": [
    "user"
  ]
}

PUT http://localhost:8081/api/Accounts/d61f91c3-d3bf-4b34-9894-e21bfa277ca4
content-Type: application/json

{
  "first_name": "Rodion",
  "last_name": "Ok",
  "username": "Fredy@129053",
  "password": "1122333",
  "roles": [
    "manager",
    "doctor"
  ]
}

DELETE http://localhost:8081/api/Accounts/6beb0d30-886f-473e-9504-f347cac58be3

GET http://localhost:8081/api/Accounts/Doctors?nameFilter=Rodi&from=1&count=10

GET http://localhost:8081/api/Accounts/Doctors/31ebc383-1c2f-460d-9b43-d080c3677706