// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавление новой истории посещений. Только админы, менеджеры и врачи. PatientUUID - аккаунт с ролью user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Добавление новой истории посещений",
                "parameters": [
                    {
                        "description": "Информация об истории",
                        "name": "history",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HistoryInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message\": \"history added successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "message\": \"invalid request/patient must be user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "message\": \"hospital/doctor/room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "message\": \"internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/Account/{uuid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение всех посещений и назначений аккаунта по ID. Только врачи и тот, кому принадлежит история",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Получение всех посещений и назначений аккаунта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID аккаунта(пациента)",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Все посещения и назначения аккаунта",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.FullHistory"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение конкретной истории посещения и назначений по ID. Только врачи и тот, кому принадлежит история",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Получение конкретной истории посещения и назначений",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID истории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о конкретной истории",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.FullHistory"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновление конкретной истории посещения по ID. Только админы, менеджеры и врачи.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Обновление истории посещения по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID истории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация ою истории",
                        "name": "history",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HistoryInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message\": \"history updated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "message\": \"invalid request/parameter id should be a number",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "message\": \"hospital/doctor/room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "message\": \"internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.FullHistory": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "doctor_uuid": {
                    "type": "string"
                },
                "hospital_uuid": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "patient_uuid": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                }
            }
        },
        "models.HistoryInfo": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "doctor_uuid": {
                    "type": "string"
                },
                "hospital_uuid": {
                    "type": "string"
                },
                "patient_uuid": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/api/History",
	Schemes:          []string{},
	Title:            "Document microservice API",
	Description:      "Document API on Go documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
